### ISSUE TITLE
Job for minetest-server.service failed

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/minetest_ynh#4]
Hi

I have a problem with minetest This error appears when minetest is reinstalled

The service failed to start

`Warning: Job for minetest-server.service failed. See 'systemctl status minetest-server.service' and 'journalctl -xn' for details.`

**Comment by ldidry** [comment]
And what `systemctl status minetest-server.service` gave you?

**Comment by Rafi594** [comment]
The result is https://framabin.org/?e3b6c2ec46e78fbb#6A3oQyUTG7xaFaXZ9U3zvBA3lIP+DK3JWJTqM+MPTdM=

**Comment by ldidry** [comment]
What is said in /var/log/minetest/minetest.log?

**Comment by Rafi594** [comment]
`admin@YunoHost:~ $ tail /var/log/minetest/minetest.log
tail: cannot open ‘/var/log/minetest/minetest.log’ for reading: No such file or directory`

**Comment by ldidry** [comment]
Look at the content of `/etc/systemd/system/multi-user.target.wants/minetest-server.service`, then `sudo su Debian-minetest -s /bin/bash` and execute the command in `ExecStart` and tell me what that say.

Also: can you give me the results of `ls -ld /etc/minetest` and `ls -lh /etc/minetest`?

**Comment by Rafi594** [comment]
`/etc/systemd/system/multi-user.target.wants/minetest-server.service`
https://framabin.org/?a51481bc60e2f8de#rxHYzqMyMEJ7yrgewnUPcKRY6Rx2n/vbsttAZeDzBZg=

`sudo su Debian-minetest -s /bin/bash`
https://framabin.org/?18fe23265abaa0aa#N1okp38RIf5WYhNSPMqBemL99fhA4hWu0gmNSj+OnhU=

`ls -ld /etc/minetest`
https://framabin.org/?b1a80d3aa93b96db#r5CPn5lFZyH26XyEFez9xcYUMLKGrDXwuqxbbglVouU=

`ls -lh /etc/minetest`
https://framabin.org/?9e255c22c92fd51b#/Ez8x4i7ZM9ctoM8i0pnGNInFklzPl7iJAtFRG7hsOc=

**Comment by ldidry** [comment]
Well… it seems to me that minetest-server is not installed… `dpkg -l | grep minetest`

**Comment by Rafi594** [comment]
`dpkg -l | grep minetest`
https://framabin.org/?8a119a3727925227#DZbfA12b9jdIx5V/j6YY1n7dAs3FzP/rX2H51PRxkJM=

I tried again to install minetest 
Here is the log
https://framabin.org/?20a920937c6ac299#RUJIMs3qdx0JZjWVpADiNbPCTpa000M3WtmYbaGTpWg=

**Comment by ldidry** [comment]
I modified the package, please retry to install it

**Comment by Rafi594** [comment]
The same problem

https://framabin.org/?1f79c034997e9291#pYRXS+sQJ6L5RME1VNehLAOt6KtIqRvv4JGWXbBv2sM=

**Comment by ldidry** [comment]
What are your options for the install? What is you version of Yunohost? Can you try to install minetest-server manually? (`sudo apt-get install minetest-server`)

**Comment by Rafi594** [comment]
My version of Yunohost is 2.5 stable

`sudo apt-get install minetest-server`
https://framabin.org/?af8f6e1436c1c9a7#cxeDCOx9G/2dcBl6So8ltQtVvfIRwxVVzwtjtUzsf5w=

**Comment by ldidry** [comment]
Forgot to say: install minetest-server from backports (that's the version I use in the package)

**Comment by Rafi594** [comment]
`sudo apt-get install -t jessie-backports minetest-server`
https://framabin.org/?53b97becca5bd50d#dtA7icBWmDN9LnuqxYh5vTOJsxgfTwrpaY2fTZBWrNc=

**Comment by ldidry** [comment]
Fork the app, put `sudo cp /etc/minetest/minetest.conf /tmp` in install or remove script, install it from your fork, and give me the content of `/tmp/minetest.conf` please.

**Comment by Rafi594** [comment]
The previous installation of minetest-server correct the problem

https://framabin.org/?9cc71c7f6f346a36#RWkwtaxUU8hipfCtXTT7JIgN+8MTqiHVXskbJonocJc=

**Comment by ldidry** [comment]
You're on a rpi… It may not use `http://http.debian.net` for the backports, so it surely is the problem for the install.

For the timeout… Verify that the firewall allows port UDP/30000 connexions. Maybe try to allow TCP/30000 too.

**Comment by Rafi594** [comment]
There are some error in the log of minetest

https://framabin.org/?45d81721cca13e22#VR4XTlOip6o3mkWRwGw0RYB5LxdI0/U3+2pYc3+EJeU=

**Comment by Rafi594** [comment]
I managed to start the game by deleting the mods folder but there is nothing in the game

https://srvmaison.nohost.me/lutim/DqrachP8/aCvldrfa.PNG

**Comment by Rafi594** [comment]
The log

**Comment by ldidry** [comment]
Please, could you uninstall the minetest ynh package, uninstall minetest-server if it still here and try again to install the ynh package? I installed a rpi 3 with ynh, made a few changes in the script and it's now working. (rpi didn't have debian gpg keyring, so it didn't want to install minetest in backports version).

**Comment by Rafi594** [comment]
The install work fine but the minetest generator in not the good only jungle trees https://framapic.org/FHCeE129NILM/mM6NLGOwPWqr.png (https://framapic.org/FHCeE129NILM/mM6NLGOwPWqr.png)

23 juin 2017 15:23 "Luc Didry"  a écrit:
	Please, could you uninstall the minetest ynh package, uninstall minetest-server if it still here and try again to install the ynh package? I installed a rpi 3 with ynh, made a few changes in the script and it's now working. (rpi didn't have debian gpg keyring, so it didn't want to install minetest in backports version).

**Comment by ldidry** [comment]
I only have snow, but I didn't try it a long time: did you travel far?

EDIT: I just tried, and I managed to go to a sand beach and a sea. You may just have to travel farther (way farther). If you still have only jungle, please open a different issue.
