### ISSUE TITLE
[HELP] Installation mods

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/minetest_ynh#8]
Suite à l'installation de Minetest (qui c'est bien déroulée) je souhaiterai maintenant y ajouter des mods...  

Mais je ne sais pas dans quels dossiers le faire :/  

En suivant le [wiki](https://wiki.minetest.net/Help:Installing_Mods) j'ai voulu installer le mod "[animals modpack](https://forum.minetest.net/viewtopic.php?t=629)" dans : 
`/usr/share/games/minetest/games/minetest_game/mods  `  

Mais quand je lance Minetest je ne le retrouve pas :( 
![2019021012 02 34](https://user-images.githubusercontent.com/11737560/52532887-df04fb00-2d2b-11e9-8332-b947c40d203d.png)

**Comment by rubenwardy** [comment]
You should install to `/home/USERNAME/.minetest/mods`

`/usr/share/games/minetest/games/minetest_game/mods ` is the *game mod directory*, and any mods in here are *game mods*, and so won't be shown in the *mods* tab.

If you update to the [Minetest 5.0.0-rc1](https://forum.minetest.net/viewtopic.php?f=18&t=22078), an unstable prerelease of Minetest 5.0.0, then you'll notice that there will be a way to install mods from a new "content" tab

**Comment by vincentux** [comment]
> You should install to `/home/USERNAME/.minetest/mods`

Je n'ai pas de dossier `.minetest` dois-je en créer un ? Sous quel "USERNAME", j'en ai plusieurs ?

**Comment by rubenwardy** [comment]
> Je n'ai pas de dossier `.minetest` dois-je en créer un ?

Oui

> Sous quel "USERNAME", j'en ai plusieurs ?

The user that will be running Minetest.

--------------

Est-ce que c'est l'endroit correcte? On dirait que c'est pour faire fonctionner un serveur, pas pour des joueurs. Installez-vous réellement en utilisant YunoHost?

Is this the right place? Looks like this is for running a server not for players. Are you actually installing using YunoHost?

**Comment by vincentux** [comment]
>On dirait que c'est pour faire fonctionner un serveur

Oui, c'est pour ça que je l'ai installé sur un VPS. Et je joue "en ligne" depuis mon pc à la maison.

>Installez-vous réellement en utilisant YunoHost?

Oui

**Comment by Rafi594** [comment]
Fixed by https://github.com/YunoHost-Apps/minetest_ynh/pull/10
