### ISSUE TITLE
Minetest 5.0

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/minetest_ynh#9]
Bonjour,
est-ce que le paquet peut installer la version 5.0 de Minetest ?

**Comment by Rafi594** [comment]
I have made a complete rework here https://github.com/YunoHost-Apps/minetest_ynh/pull/10
WIP for now don't install it in production.

**Comment by Rafi594** [comment]
Fixed by https://github.com/YunoHost-Apps/minetest_ynh/pull/10
